config/routes.rb
Rails.application.routes.draw do

  resources :universities do
    resources :faculties  do
      resources :student_libraries do
        resources :books
      end
    end
  end

  devise_for :users

  root to: "welcome#index"

end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :student_libraries
  belongs_to :university
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculties
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET universities/1/faculties
  def index
    @faculties = @university.faculties
  end

  # GET universities/1/faculties/1
  def show
  end

  # GET universities/1/faculties/new
  def new
    @faculty = @university.faculties.build
  end

  # GET universities/1/faculties/1/edit
  def edit
  end

  # POST universities/1/faculties
  def create
    @faculty = @university.faculties.build(faculty_params)

    if @faculty.save
      redirect_to([@faculty.university, @faculty], notice: 'Faculty was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT universities/1/faculties/1
  def update
    if @faculty.update_attributes(faculty_params)
      redirect_to([@faculty.university, @faculty], notice: 'Faculty was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE universities/1/faculties/1
  def destroy
    @faculty.destroy

    redirect_to university_faculties_url(@university)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculties
      @university = University.find(params[:university_id])
    end

    def set_faculty
      @faculty = @university.faculties.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def faculty_params
      params.require(:faculty).permit(:name)
    end
end

app/views/faculties/_form.html.erb
<%= form_for([@faculty.university, @faculty]) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= render 'form' %>

<%= link_to 'Show', [@faculty.university, @faculty] %> |
<%= link_to 'Back', university_faculties_path(@faculty.university) %>

app/views/faculties/index.html.erb
<h1>Listing faculties</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faculties.each do |faculty| %>
  <tr>
    <td><%= faculty.name %></td>
    <td><%= link_to 'Show', [faculty.university, faculty] %></td>
    <td><%= link_to 'Edit', edit_university_faculty_path(faculty.university, faculty) %></td>
    <td><%= link_to 'Destroy', [faculty.university, faculty], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faculty', new_university_faculty_path(params[:university_id]) %>

app/views/faculties/new.html.erb
<h1>New faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', university_faculties_path(@faculty.university) %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @faculty.name %>
</p>


<%= link_to 'Edit', edit_university_faculty_path(@faculty.university, @faculty) %> |
<%= link_to 'Back', university_faculties_path(@faculty.university) %>