config/routes.rb
Rails.application.routes.draw do

  resources :universities do
    resources :faculties  do
      resources :student_libraries do
        resources :books
      end
    end
  end

  devise_for :users

  root to: "welcome#index"

end

app/models/student_library.rb
class StudentLibrary < ApplicationRecord
  has_many :books
  belongs_to :faculty
end

app/controllers/student_libraries_controller.rb
class StudentLibrariesController < ApplicationController
  before_action :set_student_libraries
  before_action :set_student_library, only: [:show, :edit, :update, :destroy]

  # GET faculties/1/student_libraries
  def index
    @student_libraries = @faculty.student_libraries
  end

  # GET faculties/1/student_libraries/1
  def show
  end

  # GET faculties/1/student_libraries/new
  def new
    @student_library = @faculty.student_libraries.build
  end

  # GET faculties/1/student_libraries/1/edit
  def edit
  end

  # POST faculties/1/student_libraries
  def create
    @student_library = @faculty.student_libraries.build(student_library_params)

    if @student_library.save
      redirect_to([@student_library.faculty, @student_library], notice: 'Student library was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT faculties/1/student_libraries/1
  def update
    if @student_library.update_attributes(student_library_params)
      redirect_to([@student_library.faculty, @student_library], notice: 'Student library was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE faculties/1/student_libraries/1
  def destroy
    @student_library.destroy

    redirect_to faculty_student_libraries_url(@faculty)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_libraries
      @faculty = Faculty.find(params[:faculty_id])
    end

    def set_student_library
      @student_library = @faculty.student_libraries.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_library_params
      params.require(:student_library).permit(:name)
    end
end

app/views/student_libraries/_form.html.erb
<%= form_for([@student_library.faculty, @student_library]) do |f| %>
  <% if @student_library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_library.errors.count, "error") %> prohibited this student_library from being saved:</h2>

      <ul>
      <% @student_library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/student_libraries/edit.html.erb
<h1>Editing student_library</h1>

<%= render 'form' %>

<%= link_to 'Show', [@student_library.faculty, @student_library] %> |
<%= link_to 'Back', faculty_student_libraries_path(@student_library.faculty) %>

app/views/student_libraries/index.html.erb
<h1>Listing student_libraries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_libraries.each do |student_library| %>
  <tr>
    <td><%= student_library.name %></td>
    <td><%= link_to 'Show', [student_library.faculty, student_library] %></td>
    <td><%= link_to 'Edit', edit_faculty_student_library_path(student_library.faculty, student_library) %></td>
    <td><%= link_to 'Destroy', [student_library.faculty, student_library], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student library', new_faculty_student_library_path(params[:faculty_id]) %>

app/views/student_libraries/new.html.erb
<h1>New student_library</h1>

<%= render 'form' %>

<%= link_to 'Back', faculty_student_libraries_path(@student_library.faculty) %>

app/views/student_libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student_library.name %>
</p>


<%= link_to 'Edit', edit_faculty_student_library_path(@student_library.faculty, @student_library) %> |
<%= link_to 'Back', faculty_student_libraries_path(@student_library.faculty) %>