config/routes.rb
Rails.application.routes.draw do

  resources :universities do
    resources :faculties  do
      resources :student_libraries do
        resources :books
      end
    end
  end

  devise_for :users

  root to: "welcome#index"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :student_library
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_books
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET student_libraries/1/books
  def index
    @books = @student_library.books
  end

  # GET student_libraries/1/books/1
  def show
  end

  # GET student_libraries/1/books/new
  def new
    @book = @student_library.books.build
  end

  # GET student_libraries/1/books/1/edit
  def edit
  end

  # POST student_libraries/1/books
  def create
    @book = @student_library.books.build(book_params)

    if @book.save
      redirect_to([@book.student_library, @book], notice: 'Book was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT student_libraries/1/books/1
  def update
    if @book.update_attributes(book_params)
      redirect_to([@book.student_library, @book], notice: 'Book was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE student_libraries/1/books/1
  def destroy
    @book.destroy

    redirect_to student_library_books_url(@student_library)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_books
      @student_library = StudentLibrary.find(params[:student_library_id])
    end

    def set_book
      @book = @student_library.books.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:name)
    end
end

app/views/books/_form.html.erb
<%= form_for([@book.student_library, @book]) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', [@book.student_library, @book] %> |
<%= link_to 'Back', student_library_books_path(@book.student_library) %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= link_to 'Show', [book.student_library, book] %></td>
    <td><%= link_to 'Edit', edit_student_library_book_path(book.student_library, book) %></td>
    <td><%= link_to 'Destroy', [book.student_library, book], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_student_library_book_path(params[:student_library_id]) %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', student_library_books_path(@book.student_library) %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>


<%= link_to 'Edit', edit_student_library_book_path(@book.student_library, @book) %> |
<%= link_to 'Back', student_library_books_path(@book.student_library) %>