config/routes.rb
Rails.application.routes.draw do

  resources :universities do
    resources :faculties  do
      resources :student_libraries do
        resources :books
      end
    end
  end

  devise_for :users

  root to: "welcome#index"

end

app/models/university.rb
class University < ApplicationRecord
  has_many :faculties
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]
  before_action :create_university, only: [:create]

  # Whenever single object is in question this will authorize it
  before_action :authorize_single_resource
  # Whenever collection is in question this will authorize it
  before_action :authorize_index_resources


  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  protected

  def authorize_resource_actions
    super + %w( clone )
  end

  def authorize_single_resource
    super(@university)
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_university
    @university = University.find(params[:id])
  end

  def create_university
    @university = University.new(university_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def university_params
    params.require(:university).permit(:name)
  end






end

app/views/universities/_form.html.erb
<%= form_for(university) do |f| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.name %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @university.name %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>